// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC8y2rVUUwLs_unydBYb-FVFvZORLRQXos',
    appId: '1:653229579252:web:350f47e5332a8d57c537a1',
    messagingSenderId: '653229579252',
    projectId: 'chat-app-889d8',
    authDomain: 'chat-app-889d8.firebaseapp.com',
    storageBucket: 'chat-app-889d8.appspot.com',
    measurementId: 'G-3BSDZJEGCE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCo5sKU50HkUxzgigHN4attF1qcYwPvXug',
    appId: '1:653229579252:android:90e7038f8fd35791c537a1',
    messagingSenderId: '653229579252',
    projectId: 'chat-app-889d8',
    storageBucket: 'chat-app-889d8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVs6v-EFNs_1XhdH01BtRrazhWaN8JHaY',
    appId: '1:653229579252:ios:3cdc6492cc466cebc537a1',
    messagingSenderId: '653229579252',
    projectId: 'chat-app-889d8',
    storageBucket: 'chat-app-889d8.appspot.com',
    iosClientId: '653229579252-9e938d08h8c7864bm5ji302ro2n9rn0p.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDVs6v-EFNs_1XhdH01BtRrazhWaN8JHaY',
    appId: '1:653229579252:ios:26f4f042163bf388c537a1',
    messagingSenderId: '653229579252',
    projectId: 'chat-app-889d8',
    storageBucket: 'chat-app-889d8.appspot.com',
    iosClientId: '653229579252-s51b02k0pkn506m0mkbrv2fs45sb3kmu.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
